baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vivalviar.com.br/" # the base hostname & protocol for your site, e.g. http://example.com
include: ["_pages"]

# Build settings
markdown: kramdown
permalink: /:title/
theme: minima
plugins:
  - jekyll-feed

collections:
  - patrocinadores
  - banners

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
