backend:
  name: github
  repo: sandrofolk/vivalviar # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Post" # Used in the UI, e.g., "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

  - name: "page" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Pages" # Used in the UI, e.g., "New Post"
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

  - name: "patrocinador" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Patrocinador" # Used in the UI, e.g., "New Post"
    folder: "_patrocinadores" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Name", name: "name", widget: "string", tagname: "h1"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Site", name: "site", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

  - name: "banner" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Banner" # Used in the UI, e.g., "New Post"
    folder: "_banners" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title 1", name: "title1", widget: "string", tagname: "h1"}
      - {label: "Banner 1", name: "banner1", widget: "image"}
      - {label: "Link 1", name: "link1", widget: "string"}
      - {label: "Title 2", name: "title2", widget: "string", tagname: "h1"}
      - {label: "Banner 2", name: "banner2", widget: "image"}
      - {label: "Link 2", name: "link2", widget: "string"}
      - {label: "Title 3", name: "title3", widget: "string", tagname: "h1"}
      - {label: "Banner 3", name: "banner3", widget: "image"}
      - {label: "Link 3", name: "link3", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}